name: "Compute SDK Test"
description: "Test fixture Wasm modules with Viceroy"
inputs:
  config:
    description: 'Configuration JSON of the wasm module, and their expectations'
    required: true
  fixture:
    description: 'The name of the fixture to test'
    required: true

runs:
  using: "node16"
  main: dist/main.js
