name: 'Local tests'
description: 'Run tests for the provided fixture locally'

inputs:
  fixture:
    description: 'The name of the fixture to test'
    required: true
  fastly-cli-version:
    description: 'The version of the Fastli CLI app to use during testing'
    required: true
  github-token:
    description: 'The GitHub token to use for downloading the Fastly CLI'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v4
      with:
        token: ${{ inputs.github-token }}
        cli_version: ${{ inputs.fastly-cli-version }}
    - name: Download Engine
      uses: actions/download-artifact@v3
      with:
        name: engine-release
    - run: yarn
      shell: bash
    - run: cd ./integration-tests/js-compute && yarn
      shell: bash
    - run: cd ./integration-tests/js-compute && ./test.js --local
      shell: bash
