name: 'Install Rust toolchain'
description: 'Install both `rustup` and a Rust toolchain'

inputs:
  path:
    description: 'Path to directory containing rust-toolchain.toml'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Save disk space: avoid incremental compilation, and turn down
        # debuginfo from 2 to 1.
        cat >> "$GITHUB_ENV" <<EOF
        CARGO_INCREMENTAL=0
        CARGO_PROFILE_DEV_DEBUG=1
        CARGO_PROFILE_TEST_DEBUG=1
        EOF

        cd ${{ inputs.path }}
        # `rustup show` has the side-effect of downloading the toolchain
        rustup show

        if ! rustup show active-toolchain | grep -q '^nightly-'; then
          echo 'RUSTFLAGS=-D warnings' >> "$GITHUB_ENV"
        fi
