// The constructor created by cbindgen's `derive_constructor` causes this warning.
// Gecko's various uses of cbindgen silence it, so we do, too.
#ifdef __clang__
#  pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"
#endif


#ifndef rust_rasn_bindings_h
#define rust_rasn_bindings_h

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


namespace rasn {

struct PrivateKeyInfo;

struct RSAPrivateKey;

struct RSAPublicKey;

/// DEFINED BY AttributeType
struct SubjectPublicKeyInfo;

/// This type exists to transfer slices over FFI.
struct RSlice {
  const uint8_t *data;
  size_t len;

  RSlice(const uint8_t *const& data,
         size_t const& len)
    : data(data),
      len(len)
  {}

};

/// This type exists to transfer String-likes over FFI.
struct SpecString {
  uint8_t *data;
  size_t len;
  size_t cap;

  SpecString(uint8_t *const& data,
             size_t const& len,
             size_t const& cap)
    : data(data),
      len(len),
      cap(cap)
  {}

  /// Conversion to a `jsurl::SpecString`.
  operator const std::string_view() const {
    return std::string_view(reinterpret_cast<char *>(this->data), this->len);
  }
};


extern "C" {

bool decode_spki(const RSlice *data, SubjectPublicKeyInfo **out, SpecString *err);

void free_spki(SubjectPublicKeyInfo *spki);

bool decode_pkcs8(const RSlice *data, PrivateKeyInfo **out, SpecString *err);

void free_pkcs8(PrivateKeyInfo *pkcs8);

bool spki_is_rsa(const SubjectPublicKeyInfo *spki);

bool decode_public_key(const SubjectPublicKeyInfo *spki, RSAPublicKey **out, SpecString *err);

void free_pubkey(RSAPublicKey *pubkey);

bool pkcs8_is_rsa(const PrivateKeyInfo *pkcs8);

bool decode_private_key(const PrivateKeyInfo *pkcs8, RSAPrivateKey **out, SpecString *err);

void free_privkey(RSAPrivateKey *privkey);

SpecString rsa_pubkey_modulus(const RSAPublicKey *pubkey);

SpecString rsa_pubkey_exponent(const RSAPublicKey *pubkey);

SpecString rsa_privkey_modulus(const RSAPrivateKey *privkey);

SpecString rsa_privkey_exponent(const RSAPrivateKey *privkey);

SpecString rsa_privkey_private_exponent(const RSAPrivateKey *privkey);

}  // extern "C"

}  // namespace rasn

#endif  // rust_rasn_bindings_h
