// The constructor created by cbindgen's `derive_constructor` causes this warning.
// Gecko's various uses of cbindgen silence it, so we do, too.
#ifdef __clang__
#  pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"
#endif


#ifndef rust_rasn_bindings_h
#define rust_rasn_bindings_h

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


namespace rasn {

struct PrivateKeyInfo;

struct RSAPrivateKey;

struct RSAPublicKey;

/// DEFINED BY AttributeType
struct SubjectPublicKeyInfo;

/// This type exists to transfer &str-likes over FFI.
struct SpecSlice {
  const uint8_t *data;
  size_t len;

  SpecSlice(const uint8_t *const& data,
            size_t const& len)
    : data(data),
      len(len)
  {}

};

/// This type exists to transfer String-likes over FFI.
struct SpecString {
  uint8_t *data;
  size_t len;
  size_t cap;

  SpecString(uint8_t *const& data,
             size_t const& len,
             size_t const& cap)
    : data(data),
      len(len),
      cap(cap)
  {}

};


extern "C" {

bool decode_spki(const SpecSlice *data, SubjectPublicKeyInfo **out, SpecString **err);

bool decode_pkcs8(const SpecSlice *data, PrivateKeyInfo **out, SpecString **err);

bool spki_is_rsa(const SubjectPublicKeyInfo *spki);

bool decode_spki(const SubjectPublicKeyInfo *spki, RSAPublicKey **out, SpecString **err);

bool pkcs8_is_rsa(const PrivateKeyInfo *spki);

bool decode_pkcs8(const PrivateKeyInfo *spki, RSAPrivateKey **out, SpecString **err);

SpecString rsa_pubkey_modulus(const RSAPublicKey *pubkey);

SpecString rsa_pubkey_exponent(const RSAPublicKey *pubkey);

SpecString rsa_privkey_modulus(const RSAPrivateKey *privkey);

SpecString rsa_privkey_exponent(const RSAPrivateKey *privkey);

SpecString rsa_privkey_private_exponent(const RSAPrivateKey *privkey);

}  // extern "C"

}  // namespace rasn

#endif  // rust_rasn_bindings_h
