name: 'Set up a CentOS 6 container to build releases in'
description: 'Set up a CentOS 6 container to build releases in'

runs:
  using: "composite"
  steps:
    # On OSX all we need to do is configure our deployment target as old as
    # possible. For now 10.9 is the limit.
    - if: runner.os == 'macOS'
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        MACOSX_DEPLOYMENT_TARGET=10.9
        python=python3
        EOF

    # On Windows we build against the static CRT to reduce dll dependencies
    - if: runner.os == 'Windows'
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        RUSTFLAGS=-Ctarget-feature=+crt-static
        python=python
        EOF

    # ... and on Linux we do fancy things with containers. We'll spawn an old
    # CentOS container in the background with a super old glibc, and then we'll run
    # commands in there with the `$CENTOS` env var.
    - name: Set up Docker Buildx
      if: runner.os == 'Linux'
      uses: docker/setup-buildx-action@v2

    - name: Build old Linux container
      if: runner.os == 'Linux'
      uses: docker/build-push-action@v3
      with:
        context: ${{ github.action_path }}/docker
        load: true
        tags: binary-compatible-builds
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - if: runner.os == 'Linux'
      shell: bash
      run: |
        # FIXME(rust-lang/rust#80703) LD_LIBRARY_PATH shouldn't be necessary
        docker run -di --name centos -v $PWD:$PWD -v $(rustc --print sysroot):/rust:ro \
          --env LD_LIBRARY_PATH=/rust/lib \
          --env PATH="/opt/rh/devtoolset-8/root/usr/bin:$PATH:/rust/bin" \
          binary-compatible-builds

        cat >> $GITHUB_ENV <<EOF
        CENTOS=$GITHUB_ACTION_PATH/run-linux
        python=python3
        EOF
