#!/usr/bin/env bash

set -euo pipefail
exec docker run -i \
  --env PREBUILT_ENGINE="$PREBUILT_ENGINE" \
  --env PATH="/opt/rh/devtoolset-8/root/usr/bin:$PATH" \
  -v "$HOME:$HOME" --workdir "$PWD" \
  binary-compatible-builds "$@"
