# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["you@example.com"]
description = "Fastly Compute static site"
language = "javascript"
manifest_version = 3
name = "compute-js-static-site"
service_id = "w28lvGyqRRGQTcJK2rpOJL"

[local_server]

  [local_server.kv_stores]

    [local_server.kv_stores.js-docs-content]
      file = "./static-publisher/kvstore.json"
      format = "json"

[scripts]
  build = "npm run build"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.js-docs-content]
