/*
 * Generated by @fastly/compute-js-static-publish.
 */

// Commented items are defaults, feel free to modify and experiment!
// See README for a detailed explanation of the configuration options.

/** @type {import('@fastly/compute-js-static-publish').PublishContentConfig} */
const config = {
  rootDir: "../build",
  // excludeDirs: [ './node_modules' ],
  // excludeDotFiles: true,
  // includeWellKnown: true,
  // kvStoreAssetInclusionTest: (assetKey) => true,
  // contentCompression: [ 'br', 'gzip' ], 
  // contentTypes: [
  //   { test: /.custom$/, contentType: 'application/x-custom', text: false },
  // ],

  // Server settings are saved to the KV Store per collection
  server: {
    publicDirPrefix: "",
    staticItems: [],
    allowedEncodings: ['br', 'gzip'],
    spaFile: false,
    notFoundPageFile: "/404.html",
    autoExt: [],
    autoIndex: ["index.html", "index.htm"],
  },
};

export default config;
