/*
 * Generated by @fastly/compute-js-static-publish.
 */

/** @type {import('@fastly/compute-js-static-publish').StaticPublishRc} */
const rc = {
  kvStoreName: "js-docs-content",
  publishId: "default",
  defaultCollectionName: "live",
  staticPublisherWorkingDir: "./static-publisher",
};

export default rc;
